### ISSUE TITLE
Dr. Zheng proposed model design

### ISSUE THREAD

**Issue by italobusi** [italobusi/ietf-network-inventory#21]
Dr. Zheng from China Unicom have a different idea about the model design. He prefers to define the inventory objects directly and follow the relationship like:

```
+inventory
   +--equipment-rooms
   |    +--racks
   |     |    +--shelves
   |     |     |   +--slots
   |     |     |    |  +--subslots
   |    +--network-elements
   |     |   +--boards
   |     |    |    +--ports
```

_Originally posted by @YuChaode in https://github.com/italobusi/ietf-network-inventory/issues/19#issuecomment-947303203_

**Comment by YuChaode** [comment]
This model is updated, please refer to the slide in issue#32.
