### ISSUE TITLE
The child-ref & parent-ref in component  are pointing to wrong object

### ISSUE THREAD

**Issue by YuChaode** [italobusi/ietf-network-inventory#23]
The child-ref and parent-ref of component should point to the child compoent and parent component instead of network element.
![20211102-151451(WeLinkPC)](https://user-images.githubusercontent.com/25008042/139802136-c160e021-045b-4080-80e8-13f6b3141435.png)

**Comment by italobusi** [comment]
fixed with https://github.com/italobusi/ietf-network-inventory/commit/0df1efcafc86ee303207be958146aac259752166
