### ISSUE TITLE
Model traversal between inventory and topology

### ISSUE THREAD

**Issue by anton1688** [italobusi/ietf-network-inventory#31]
with the current data model there is no way to traverse from the topology to the inventory data model. 

such traversal at the moment necessitates that an implementor MUST expose a white topology (optionally in addition to other abstracted topologies) in order to allow a reference/pointer to point between topological I/O elements (ports) to their inventory data. this could potentially lead to scale issues.

data model should consider full and abstracted topologies.

**Comment by italobusi** [comment]
Duplicated with issue #33
