### ISSUE TITLE
Scope of the Inventory: Optical and/or IP

### ISSUE THREAD

**Issue by italobusi** [italobusi/ietf-network-inventory#4]
Check whether the scope of the inventory model should be limited only to Optical networks or be applicable to both IP and Optical networks

**Comment by oscargdd** [comment]
RFC 8348 is agnostic to the technology... At least the "basis" should be as agnostic as possible.

**Comment by italobusi** [comment]
**2021-10-06 Network Inventory Call**

Oscar/Jeff B./Victor thinks that the network inventory model should be technology-agnostic and applicable to at least Optical and IP

Aihua: in order to understand the applicability to IP, we need to investigate which objects are of interest to the inventory for IP networks

Let's define an high-level structure and then investigate that it could support IP networks as well

Which WG should the draft be targeted?

* CCAMP: applicability to Optical as well as WG which has more LS relationship (like the Alarm Management)
* TEAS: originate from a gap in the ACTN POI analysis
* Netmod: the origin of RFC8348

General agreement to submit the initial draft to CCAMP WG

**Comment by italobusi** [comment]
The agreed scope is to define a generic model applicable to Optical, IP and MW
