### ISSUE TITLE
Where to put the component list?

### ISSUE THREAD

**Issue by italobusi** [italobusi/ietf-network-inventory#9]
Evaluate whether the component list shall be under the node (i.e., NE) or under the network

Note that equipment rooms and racks (see #8) do not belong to any NE

**Comment by italobusi** [comment]
If the component list is placed under the network with a leafref to the NE the component belongs to, it would be straightforward to retrieve the list of components of a given type within the whole network as well as within a given NE (using filters).

If the component list is placed under the NE, it would be straightforward to retrieve the list of components of a given type within a given NE (using filters) but it would require multiple queries to get the list of components of a given type within the whole network.

**Comment by YuChaode** [comment]
I wrote an email to the RESTCONF authors, one of them replied that the filtering of list on the server side is not defined in standard. The usage of filter parameter in this URL is not correct. I think maybe we need to define a RPC operation to do the filtering.
